version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: currencies-nginx
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
    networks:
      - nbrb-currencies-network

  backend:
    build:
      context: ./backend/
      dockerfile: Dockerfile
      target: prod
    container_name: currencies-backend
    volumes:
      - ./backend/:/app:cached
    depends_on:
      - db
      - redis
    environment:
      REDIS_ADDRESS: redis:6379
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: ${MYSQL_USER}
      DB_PASS: ${MYSQL_PASSWORD}
      DB_NAME: ${MYSQL_DB}
      GIN_MODE: "release"
    restart: always
    networks:
      - nbrb-currencies-network

  db:
    image: mysql:latest
    container_name: currencies-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./db:/var/lib/mysql
    networks:
      - nbrb-currencies-network

  redis:
    container_name: currencies-redis
    hostname: redis
    image: redis:latest
    volumes:
      - ./redis:/data
    restart: always
    networks:
      - nbrb-currencies-network

  swagger:
    image: swaggerapi/swagger-ui
    container_name: currencies-swagger-ui
    environment:
      API_URL: http://localhost/api/swagger/docs.json
    ports:
      - "8888:8080"
    networks:
      - nbrb-currencies-network

networks:
  nbrb-currencies-network:
    driver: bridge